### ISSUE TITLE
isbnlib.mask crashes for ISBN 9786131796364

### ISSUE THREAD

**Issue by EmilStenstrom** [xlcnd/isbnlib#18]
I'm getting a crash for this specific ISBN number:
```
>>> isbnlib.mask("9786131796364")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/EmilStenstrom/Envs/boktraven/lib/python2.7/site-packages/isbnlib/_ext.py", line 16, in mask
    return msk(isbn, separator)
  File "/Users/EmilStenstrom/Envs/boktraven/lib/python2.7/site-packages/isbnlib/_msk.py", line 45, in msk
    if l[0] <= int(sevens) <= l[1]:
TypeError: 'int' object has no attribute '__getitem__'
```
I would expect None as a return value if it's an invalid ISBN.

**Comment by xlcnd** [comment]
Thanks.

A bug in the program that makes the 'data ranges' cause this. It writes single tuples without the ','.  And recently, have been issued ISBNs with single blocks... so this should affect `info` too!

OK, thanks again, I will fix it.

**Comment by EmilStenstrom** [comment]
Thanks to you! :)
